[pytest]
testpaths = tests
norecursedirs =
    .git
    .venv
    venv
    whisper_env
    align_env
    demucs_env
    lyrics-align-env
    master_karaoke_env
    mfa_env
    gentle-0.11.0
    gentle-full
    gentle_broken_1
addopts = -ra
