#!/bin/sh
# Regenerate the pre-optimized web icons committed under web/src/ from the
# pristine 1024px master at assets/icon.png.
#
# Why these are committed instead of generated by web/build.mjs: sips emits
# unoptimized truecolor PNGs, and the service worker's install precache
# (CORE_ASSETS in web/src/sw.js) re-downloads all three icons on every deploy
# on every device. Quantizing (pngquant, quality floor 88) + lossless squeeze
# (oxipng) took the icon payload from ~1.5 MB to ~0.6 MB with no visible
# change at icon display sizes (verified 2026-08-02). Committing the outputs
# keeps builds deterministic and keeps pngquant/oxipng out of CI's toolchain.
#
# Run this ONLY when the icon artwork itself changes, then commit the three
# web/src/icon*.png outputs. Tools: sips is built into macOS;
#   brew install pngquant oxipng
set -eu

cd "$(dirname "$0")/.."

MASTER=assets/icon.png
[ -f "$MASTER" ] || { echo "ERROR: $MASTER not found" >&2; exit 1; }
for tool in sips pngquant oxipng; do
  command -v "$tool" >/dev/null 2>&1 || {
    echo "ERROR: $tool not found (brew install pngquant oxipng)" >&2
    exit 1
  }
done

TMPDIR_ICONS=$(mktemp -d)
trap 'rm -rf "$TMPDIR_ICONS"' EXIT

# 1024: quantize the master directly (no resize).
pngquant --speed 1 --quality 88-100 --strip --force \
  --output web/src/icon.png "$MASTER"
oxipng -o max --strip safe -q web/src/icon.png

# 192 / 512: resize the PRISTINE master first, quantize last, so the derived
# sizes never go through two generations of palette loss.
for size in 192 512; do
  sips -z "$size" "$size" "$MASTER" --out "$TMPDIR_ICONS/resized-$size.png" >/dev/null
  pngquant --speed 1 --quality 88-100 --strip --force \
    --output "web/src/icon-$size.png" "$TMPDIR_ICONS/resized-$size.png"
  oxipng -o max --strip safe -q "web/src/icon-$size.png"
done

ls -l web/src/icon.png web/src/icon-192.png web/src/icon-512.png
echo "Done. Commit the three web/src/icon*.png files."
